<a href="https://colab.research.google.com/github/9Y7H/py-13/blob/master/Homework/Summary_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

>>>[라이브러리 - overview](#scrollTo=Oowy-rXCINrL)

>>>[라이브러리 - numpy](#scrollTo=lwkU4jfreQMo)

>>>>>[numpy란?](#scrollTo=lwkU4jfreQMo)

>>>>>[numpy vs list](#scrollTo=lwkU4jfreQMo)

>>>[라이브러리-numpy vector(1차원 배열)](#scrollTo=o_9t87yDgkeg)

>>>>>[벡터(vector) 생성](#scrollTo=o_9t87yDgkeg)

>>>>>[벡터(vector) 산술연산](#scrollTo=sx4n8wUylHF-)

>>>[라이브러리-numpy matrix(행렬)](#scrollTo=G7AYXs34kGfm)

>>>>>[행렬(matrix) 생성](#scrollTo=G7AYXs34kGfm)

>>>>>[형 변환(reshape)](#scrollTo=kkGFjkzylNo5)

>>>[리이브러리-numpy 행렬 곱(dot product)](#scrollTo=njx2ym96m7cu)

>>>>>[행렬 곱(dot product)(1)](#scrollTo=njx2ym96m7cu)

>>>>>[행렬 곱(dot product)(2)](#scrollTo=k9i3f7eqoylr)

>>>[라이브러리-numpy broadcast](#scrollTo=1iRn5ED-p2H1)

>>>[라이브러리-nupmy 전치행렬(transpose)](#scrollTo=Kv0MmfNvqz_N)

>>>>>[전치행렬(transpose)](#scrollTo=Kv0MmfNvqz_N)

>>>[라이브러리-numpy 행렬 indexing/ slicing](#scrollTo=7PEwUy13ts0A)

>>>>>[행렬 원소 접근(1)](#scrollTo=7PEwUy13ts0A)

>>>[라이브러리-numpy 행렬 iterator](#scrollTo=subzM4ZZvYTb)

>>>>>[행렬 원소 접근(2)](#scrollTo=subzM4ZZvYTb)



###라이브러리 - overview

In [1]:
import numpy

A = numpy.array([1,2])

print("A ==", A, ",type ==",type(A))

A == [1 2] ,type == <class 'numpy.ndarray'>


In [2]:
import numpy as np

A = np.array([1,2])

print("A ==", A, ",type ==",type(A))

A == [1 2] ,type == <class 'numpy.ndarray'>


In [3]:
from numpy import exp

result = exp(1)

print("result ==", result,", type ==", type(result))

result == 2.718281828459045 , type == <class 'numpy.float64'>


In [4]:
from numpy import *

result = exp(1) + log(1.7) + sqrt(2)

print("result ==", result,", type ==", type(result))

result == 4.663123641894311 , type == <class 'numpy.float64'>


###라이브러리 - numpy


#####numpy란?

=>머신러닝 코드 개발할 경우 자주 사용되는 벡터, 행렬 등을 표현하고 연산될 때 반드시 필요한 라이브러리

#####numpy vs list

=>머신러닝에서 숫자, 사람, 동물 등의 인식을 하기 위해서는 이미지(image)데이터를 행렬(matrix)로 변환하는 것이 중요

=>행렬(matrix)을 나타내기 위해서는 리스트(list)를 사용할 수도 있지만, 행렬 연산이 직관적이지 않고 오류 가능성이 높기 때문에, 행렬 연산을 위해서는 numpy 사용이 필수임

In [0]:
import numpy as no

In [0]:
#리스트로 행렬 표현

A = [ [1,0], [0,1] ]
B = [ [1,1], [1,1] ]

In [7]:
A + B #행렬 연산이 아닌 리스트 연산

[[1, 0], [0, 1], [1, 1], [1, 1]]

In [0]:
#numpy, matrix, 직관적임

A = np.array([ [1,0], [0,1] ])
B = np.array([ [1,1], [1,1] ])

In [9]:
A + B #행렬 연산

array([[2, 1],
       [1, 2]])

###라이브러리-numpy vector(1차원 배열)

#####*  벡터(vector) 생성

=>vector는 np.array([...])를 사용하여 생성함(import numpy as np)

=>머신러닝 코드 구현시, 연산을 위해서 vetcor, matrix등의 형상(shape),차원(dimension)을 확인하는 것이 필요함


In [0]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

In [11]:
#vector A, B 출력
print("A ==", A,", B ==",B)

A == [1 2 3] , B == [4 5 6]


In [12]:
#vector A, B 형상 출력 => shape
print("A.shape ==",A.shape,", B.shaape ==",B.shape)

A.shape == (3,) , B.shaape == (3,)


In [13]:
#vector A, B 차원 출력 => ndim
print("A.ndim ==",A.ndim,", B.ndim ==",B.ndim)

A.ndim == 1 , B.ndim == 1


#####*   벡터(vector) 산술연산

=>vector 간 산술연산(+, -, *, /)은 벡터의 각각의 원소에 대하여 행해짐

In [14]:
#vector 산술 연산

print("A + B ==", A+B)
print("A - B ==", A-B)
print("A * B ==", A*B)
print("A / B ==", A/B)

A + B == [5 7 9]
A - B == [-3 -3 -3]
A * B == [ 4 10 18]
A / B == [0.25 0.4  0.5 ]


###라이브러리-numpy matrix(행렬)


#####*   행렬(matrix) 생성

=>matrix는 vector와 마찬가지로 np.array([ [...],[...], ...])를 사용하여 생성함(import numpy as np)


In [0]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[-1, -2, -3],[-4,-5,-6]])

In [16]:
#matrix A, B 형상 출력 => shape
print("A.shape ==",A.shape,", B.shape ==",B.shape)

A.shape == (2, 3) , B.shape == (2, 3)


In [17]:
#matrix A, B 차원 출력 => ndim
print("A.ndim ==",A.ndim,", B.ndim ==",B.ndim)

A.ndim == 2 , B.ndim == 2


#####*   형 변환(reshape)

=>vector를 matrix로 변경하거나 matrix를 다른 형상의 matrix로 변경하기 위해서는 reshape() 사용하여 행렬의 shape을 변경하여야 함

In [0]:
C = np.array([1, 2, 3])

In [19]:
#vector C형상 출력 => shape
print("C.shape ==", C.shape)

C.shape == (3,)


In [0]:
#vector를 (1,3) 행렬로 형 변환
C = C.reshape(1, 3)

In [21]:
print("C.shape ==", C.shape)

C.shape == (1, 3)


###리이브러리-numpy 행렬 곱(dot product)

#####*   행렬 곱(dot product)(1)

=>A행렬과 B행렬의 행렬 곱(dot product)는 np.dot(A,B) 나타내며, 행렬 A의 열 벡터와 B 행렬의 행 벡터가 같아야 함

=>만약 같지 않다면 reshape 또는 전치행렬(transpose)등을 사용하여 형 변환을 한 후에 행렬 곱 실행해야 함



In [0]:
A = np.array([ [1, 2, 3], [4, 5, 6]]) #2X3 행렬
B = np.array([ [-1, -2], [-3, -4], [-5, -6] ]) #3X2 행렬

In [0]:
#(2X3) dot product (3X2) ==(2X2) 행렬
C = np.dot(A, B) #행렬 곱 수행

In [24]:
#matrix A, B 형상 출력 => shape
print("A.shape ==", A.shape,", B.shape ==", B.shape)
print("C.shape ==",C.shape)
print(C)

A.shape == (2, 3) , B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]




#####*   행렬 곱(dot product)(2)
1.행렬곱 조건을 만족하는 다양한 크기의 행렬을 연속으로 만든다

2.행렬 곱을 연속으로 계산

3.결과값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용

*다양한 특성을 갖는 필터 개발이 불가능*



###라이브러리-numpy broadcast
=>numpy에서는 크기가 다른 두 행렬 간에서도 사칙연산(+, -, *, /)을 할 수 있는데 이를 브로드캐스트(broadcast)라고 지칭함 

=> 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산

In [0]:
A = np.array([ [1, 2], [3, 4]])
b =5

In [26]:
print(A+b)

[[6 7]
 [8 9]]


In [0]:
C = np.array([ [1, 2],[3, 4] ])
D = np.array([4, 5])

In [28]:
print(C+D)

[[5 7]
 [7 9]]


###라이브러리-nupmy 전치행렬(transpose)


#####*  전치행렬(transpose)

=>어떤 행렬의 전치행렬(transposed matrix)은 원본 행렬의 열은 행으로, 행은 열로 바꾼 것으로서, 원본 행렬을 A라고 하면 A^T로 나타냄

=>즉, 1행은 1열로 바꾸고 2행은 2열로, 3행은 3열로 바꾼 행렬을 의미



In [0]:
A = np.array([ [1, 2],[3, 4],[5, 6] ]) #3X2 행렬
B = A.T #A의 전치행렬, 2X3 행렬

In [30]:
print("A.shape ==",A.shape,", B.shape ==",B.shape)
print(A)
print(B)

A.shape == (3, 2) , B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [0]:
#vector 전치행렬

C = np.array([ 1, 2, 3, 4, 5]) #vector, matrix 아님
D = C.T #C는 vector 이므로 transpose 안됨

In [0]:
E = C.reshape(1,5) #1X5 matrix
F = E.T #E의 전치행렬

In [33]:
print("C.shape ==", C.shape,", D.shape ==", D.shape)
print("E.shape ==", E.shape,", F.shape ==", F.shape)
print(F)

C.shape == (5,) , D.shape == (5,)
E.shape == (1, 5) , F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


###라이브러리-numpy 행렬 indexing/ slicing


#####*   행렬 원소 접근(1)

=>행렬 원소를 명시적(explicit)으로 접근하기 위해서는 리스트(list)에서처럼, 인덱스/슬라이싱 모두 사용가능 함



In [0]:
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)

In [35]:
print("A.shape ==",A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [36]:
print("A[0, 0] ==",A[0, 0],", A[0][0] ==",A[0][0]) #A[0,0] 과 A[0][0]의 값을 출력
print("A[2, 1] ==",A[2, 1],", A[2][1] ==",A[2][1]) #A[2,1] 과 A[2][1]의 값을 출력

A[0, 0] == 10 , A[0][0] == 10
A[2, 1] == 60 , A[2][1] == 60


In [37]:
print("A[0:-1, 1:2] ==", A[0:-1, 1:2])#배열 A 의 인덱스 0번부터 마지막 값을 뺀 인덱스 중
                                      # 인덱스 1번부터 2버을를 포함하지 않은 값을 출력

A[0:-1, 1:2] == [[20]
 [40]]


In [38]:
print("A[:,0] ==",A[:,0])
print("A[:, :] ==",A[:, :])

A[:,0] == [10 30 50]
A[:, :] == [[10 20]
 [30 40]
 [50 60]]


###라이브러리-numpy 행렬 iterator


#####*   행렬 원소 접근(2)

=>명시적(explicit) 인덱스/ 슬라이싱 이외에, 행렬 모든 원소를 access하는 경우에는 iterator 사용가능



In [39]:
import numpy as np

A = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])

print(A,"\n")
print("A.shape ==", A.shape,"\n")

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 



In [40]:
#행렬 A의 itrator 생성

it = np.nditer(A,flags=['multi_index'],op_flags=['readwrite'])

while not it.finished:
  idx = it.multi_index
  
  print("current value => ",A[idx])
  
  it.iternext()

current value =>  10
current value =>  20
current value =>  30
current value =>  40
current value =>  50
current value =>  60
current value =>  70
current value =>  80
